# FINE TUNING CONFIGURATION FILE
modality: mmwave|depth|rgb

protocol: protocol1

data_unit: sequence

manual_split:
  train_dataset:
    split: training
    scenes: None
    subjects: ['S05', 'S06', 'S15', 'S16', 'S25', 'S26', 'S35', 'S36'] # 2 subjects
    #'S05', 'S06', 'S15', 'S16', 'S25', 'S26', 'S35', 'S36'
    actions: ['A01', 'A02', 'A03', 'A04', 'A05', 'A06', 'A07', 'A08', 'A09','A10', 'A11', 'A12', 'A13', 'A14','A15', 'A16', 'A17', 'A18', 'A19', 'A20', 'A21', 'A22', 'A23', 'A24', 'A25', 'A26', 'A27']
    
    #[A01, A02, A03, A04, A05, A06, A07, A08, A09, A10, A11, A12, A13, A14, A15, A16, A17, A18, A19, A20, A21, A22, A23, A24, A25, A26, A27]
  val_dataset:
    split: validation
    scenes: None
    subjects: [S21]
    actions: [A01]

split_to_use: manual_split

init_rand_seed: 0
train_loader:
  batch_size: 10
validation_loader:
  batch_size: 1
output_folder: ./ckpt/
